version: '3.9'

services:
  simple-grocery-list-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=grocery
    volumes:
      - type: bind
        source: ./log/data
        target: /log
    networks:
      - app-net

networks:
  app-net:
    external:
      name: grocery-net
