FROM openjdk:17

EXPOSE 8080

ENV POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
    POSTGRES_USER="${POSTGRES_USER}" \
    POSTGRES_DB="${POSTGRES_DB}"

COPY target/simple-grocery-list.*.jar simple-grocery-list.jar

ENTRYPOINT ["java", "-jar", "simple-grocery-list.jar"]